### ISSUE TITLE
warning to contribute (fastlz) - but where to add

### ISSUE THREAD

**Issue by bizulk** [kozross/awesome-c#111]
Hello !
Maybe because I am newbie to github contributing but there something I"m missing :
I want to add fastlz as C compressor that I managed to build easily for uC architecture (cortexM4)

- I forked your project.
- On my  project the readme is empty, it says that the repo has moved to notabug
- I seems that te github repo continues tu be maintained,

should I add a pull req on notabug ?
Oh by the way I noticed that the SEI CERT C coding Standard is not correct.

**Comment by kozross** [comment]
@bizulk Thanks for notifying me about the CERT C Coding Standard link being broken - I will fix it ASAP. Look forward to your contribution!

**Comment by bizulk** [comment]
question closed i think
