### ISSUE TITLE
Rapidstring link broken.

### ISSUE THREAD

**Issue by TryExceptElse** [kozross/awesome-c#119]
The rapidstring link is currently broken. 
The user (boyerjohn) seems to have disappeared from Github.

**Comment by kozross** [comment]
Thank you for reporting this - I shall push a fix shortly removing this from the list.

**Comment by bizulk** [comment]
also reported in awesomecpp, someone pointed out this cloned repo : https://github.com/mathchq/rapidstring

**Comment by TryExceptElse** [comment]
That is an option. It doesn't seem to have any activity in the last year however.

**Comment by bizulk** [comment]
In that particular case I may let that project disapears as I don't see usage for it.

> "It doesn't seem to have any activity in the last year however."

And then ?
Is the project stable and mature, not marked deprecated, are people using it or interested to ?
The api is quite good quality (even better than some still referenced project) to me, and has those github tags that evaluate the project to something clean.
