### ISSUE TITLE
vector.h link leads to wrong url?

### ISSUE THREAD

**Issue by ryanavella** [kozross/awesome-c#127]
The vector.h link leads to this url for the icc compiler:

https://sites.google.com/site/lccretargetablecompiler/

I'm wondering if perhaps this was the intended vector.h?

https://github.com/swenson/vector.h

I also found this vector.h, but I'm less certain that this could be the intended header

https://gitlab.com/ankushjp4/vector.h

**Comment by kozross** [comment]
@ryanavella Thanks for that - this was due to a numbering mix-up in the links. I've now fixed it.
