### ISSUE TITLE
Add libhv to "Networking and Internet"

### ISSUE THREAD

**Issue by ithewei** [kozross/awesome-c#132]
[libhv](https://github.com/ithewei/libhv.git) - Cross-platform event loop library. [BSD-3-Clause]

**Comment by kozross** [comment]
@ithewei Could you make a PR for this please?

**Comment by ithewei** [comment]
@kozross https://github.com/kozross/awesome-c/pull/133

**Comment by ithewei** [comment]
Thanks for merging PR #133
