### ISSUE TITLE
cimgui

### ISSUE THREAD

**Issue by nickscha** [kozross/awesome-c#139]
Under "Graphical User Interface" I would propose to add the "cimgui" library (MIT licencse). 
https://github.com/cimgui/cimgui is a C-Binding based on https://github.com/ocornut/imgui and is a cross platform UI library which works pretty well with different graphic libraries (opengl, vulkan...).

It is an Immediate Mode UI library and could be added below the "nuklear" reference which is an alternative UI library.

**Comment by kozross** [comment]
Thanks for that! I'm a little unclear though - you say that this requires a C++ compiler, which would put it out of scope for awesome-c.

**Comment by nickscha** [comment]
Ok. yes, it requires a c++ compiler.
