### ISSUE TITLE
Learning resources for C - suggestion and review

### ISSUE THREAD

**Issue by kozross** [kozross/awesome-c#16]
The Learning, Reference and Tutorial section is a bit threadbare in places, and also, given that I'm a relatively-intermediate C user, I'm not sure if the resources there are any good.

Thus, it'd be great if someone could:

1. Suggest more (both on and offline).
2. Tell me if any of the stuff up there is awful, and *why*.

For reasons of dodgy business practices and mistreatment of its staff, I will *not* link to Amazon. Thus, if you give me an Amazon link, it probably won't make it in unless I can find an alternative.

**Comment by lbraglia** [comment]
Hi, thanks for the list...

could comp.lang.c Frequently Asked Questions be useful?

http://c-faq.com/

best, 
  Luca

**Comment by kozross** [comment]
Seems good - will add.

**Comment by lbraglia** [comment]
Some interesting tutorials about parallel programming i found [here](https://computing.llnl.gov/?set=training&page=index#training_materials)  (didn't read them yet but seem complete, updated and already cited a lot on google) 

https://computing.llnl.gov/tutorials/parallel_comp/  (however this is not C-specific)
https://computing.llnl.gov/tutorials/pthreads/
https://computing.llnl.gov/tutorials/openMP/
https://computing.llnl.gov/tutorials/mpi/

**Comment by lbraglia** [comment]
coding standards (recommendation/rules) for safe programming from cert

https://www.securecoding.cert.org/confluence/display/seccode/CERT+C+Coding+Standard

**Comment by kozross** [comment]
These are excellent! I'll add them all, except the parallel computing one (as it's not specific to C).

**Comment by kozross** [comment]
Closing to avoid encouragement of contribution in the wrong place.
