### ISSUE TITLE
Numerical and Parallel resources

### ISSUE THREAD

**Issue by spott** [kozross/awesome-c#23]
Numerical:

PETSc:  The Portable, Extensible Toolkit for Scientific computation.

SLEPc: The Scalable Library for Eigenvalue Problem Computations.

Parallel:

OpenMPI -- Message passing interface implementation, and MPICH (which is also open sourced I believe).

**Comment by kozross** [comment]
Thanks - these have all been added to the [NotABug][1] version.

[1]: https://notabug.org/koz.ross/awesome-c
