### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [kozross/awesome-c#24]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

I know your repo isn't on GitHub anymore, but you should reconsider.  We have alot of people here that want to help!

**Comment by kozross** [comment]
@jeffreyjackson First of all, thanks for your interest in Awesome C! I believe that working together is important, but at the same time, I am all about free software (and take pride in my use of that particular term over the business-appeasing 'open source'). Therefore, I cannot be convinced to move back to GitHub as long as they retain proprietary components.

However, if you guys were to consider moving yourselves to [NotABug][1], which is a fully-free alternative to GitHub, I would be all for it.

[1]: https://notabug.org/

**Comment by jeffreyjackson** [comment]
@kozross interesting, your position is because @github isn't open source therefore you dont want to use it?

thank you for your feedback!
