### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by benwaffle** [kozross/awesome-c#25]
I know it's on notabug now but I don't want to sign up

- http://cdecl.org
- libmpv (https://github.com/mpv-player/mpv)

**Comment by kozross** [comment]
I'll definitely add cdecl. Is it possible to build libmpv without the rest of MPV?

**Comment by benwaffle** [comment]
not sure but there are video players such as [this](http://bakamplayer.u8sand.net/index.php) that use libmpv

**Comment by kozross** [comment]
@benwaffle Thanks - it's been added too. Closing.
