### ISSUE TITLE
Broken Links since Aug 22, 2018 

### ISSUE THREAD

**Issue by P-p-H-d** [kozross/awesome-c#77]
After commit 0050811ab9cf2d03c9a59c988edf29a5663be4b1,
many links of README.md do not link anymore to the right URL (ex: zlib points to rabbitmq)
It seems it has introduced a shift in the link table from 173 to 543.

**Comment by kozross** [comment]
Whoops! That was a bad merge from an earlier commit. Thank you for bringing this to my attention - I will fix it as soon as I can.

**Comment by kozross** [comment]
Should be fixed with [``746aba6``][https://github.com/kozross/awesome-c/commit/746aba606a2fb2cb7b801845753f7a2ebdda6f17]. Please let me know if anything else is broken; once again, thank you for your prompt response.
