### ISSUE TITLE
libav

### ISSUE THREAD

**Issue by myd7349** [kozross/awesome-c#91]
https://github.com/libav/libav

**Comment by kozross** [comment]
This list contains FFMPEG, which, as I understand it, is a more widely-used, and more feature-rich, version of this library. Is there something about libav that makes it worth including relative that?

**Comment by tybilgic** [comment]
Featurewise there shouldn't be anything that makes libav worth including (over FFmpeg). FFmpeg merges  everything from libav.

**Comment by myd7349** [comment]
Thanks! I will close it.
